### ISSUE TITLE
Kundur under-damped modes

### ISSUE THREAD

**Issue by xiaojiangsi** [CURENT/andes#425]
the document says:

The Kundur's two-area system has under-damped modes and two coherent groups of generators. It is
suitable for oscillation study and transient stability studies.

 how to do that? how to set the under-damped mode?

**Comment by cuihantao** [comment]
Underdamped modes can be found by performing an eigenvalue analysis. You can do `andes run ... -r eig` and inspect the output `_eig.txt` file for the oscillation modes.

**Comment by cuihantao** [comment]
This does not seem to be an issue so closing for now. Feel free to reopen it, or use "Discussions" if you have questions.
