### ISSUE TITLE
Documentation not being updated after repository transfer

### ISSUE THREAD

**Issue by cuihantao** [CURENT/andes#426]
### Discussed in https://github.com/CURENT/andes/discussions/421

<div type='discussions-op-text'>

<sup>Originally posted by **jinningwang** March 12, 2023</sup>
Hello Hantao,

Just a kind reminder that I found that the ANDES documentation has not been updated to v1.8.7.
Maybe you need to update the git source in ReadTheDocs and the link in the documentation?

Regards,
Jinning</div>

**Comment by cuihantao** [comment]
It turns out that the issue is not due to repository transfer but due to readthedocs's recent update on fail policy. Previously, when PDF build fails, the readthedocs build will complete as long as a PDF file is generated. It will not be the case in the future. 

Efforts are needed to edit out the issues in the documentation to pass LaTeX build. See https://github.com/readthedocs/readthedocs.org/issues/10150  FYI. @jinningwang

**Comment by jinningwang** [comment]
Thanks for the information!

**Comment by jinningwang** [comment]
I'll try to fix this later this week.

**Comment by cuihantao** [comment]
It is likely a different issue this time. The previous issue was due to failed PDF builds. Readthedocs temporaily lifted strict requirement on successful PDF builds; this issue will come back when RTD decides to enforce it again.

This time, it might be due to a package version issue. Check if RTD uses a separate `requirements.txt` file and updated the affected ones.
