### ISSUE TITLE
Problems in the simulation of generator frequency

### ISSUE THREAD

**Issue by Cmt111** [CURENT/andes#443]
I encountered problems in the simulation of generator frequency. I used the file
” ss = andes.load(andes.get_case("ieee14/ieee14_full.xlsx"), setup=False, default_config=True)”.
I increased the active power of the GENROU3 by 0.2p.u. at 7s. It can be seen from the figure that the frequency of the GENROU3 increased. 
I am expecting to see that the frequency of five generators will be consistent. But it is strange that the frequency of GENROU3 will not be reduced to be consistent with the other four generators. Can you help me find out what is the reason for this?

WINDOWS
ANDES Version 1.8.7

![image](https://user-images.githubusercontent.com/131362179/233357056-5323caed-1752-41bb-a974-aa533a32a358.png)

**Comment by Cmt111** [comment]
Here is the program.

import andes
import matplotlib
import matplotlib.pyplot as plt
ss = andes.load(andes.get_case("ieee14/ieee14_full.xlsx"), setup=False, default_config=True)
ss.setup()
ss.PQ.config.p2p = 1
ss.PQ.config.q2q = 1
ss.PQ.config.p2z = 0
ss.PQ.config.q2z = 0
ss.PQ.pq2z = 0
ss.PFlow.run()
ss.TDS.config.tf = 7
ss.TDS.config.criteria = 0 
ss.TDS.run()
ss.GENROU.set(src='u', idx='GENROU_3', attr='v', value=0.6)

ss.TDS.config.tf = 55
ss.TDS.config.criteria = 0 
ss.TDS.run()

matplotlib.use('TkAgg')

ss.TDS.load_plotter()
ss.TDS.plt.plot(ss.GENROU.omega,a=(0, 1, 2, 3, 4), ylabel="Generator Frequency(Hz)",grid=True,ytimes=60)
ss.TDS.run()

**Comment by jinningwang** [comment]
I don't think this is a bug. You might need to check ``ss.GENROU.set(src='u', idx='GENROU_3', attr='v', value=0.6)``. I am confused about this.

**Comment by Cmt111** [comment]
> I don't think this is a bug. You might need to check `ss.GENROU.set(src='u', idx='GENROU_3', attr='v', value=0.6)`. I am confused about this.

Thank you for your response. Maybe my expression is wrong. I use “ss.GENROU.set(src='u', idx='GENROU_3', attr='v', value=0.6)” to achieve the GENROU3 to increase the active power of 0.2p.u. at 7s(The original active power of the GENROUr is 0.4p.u.). How to achieve it, please?

**Comment by cuihantao** [comment]
`u` is connectivity status that should only be 0 or 1. Setting `u` to non-binary values will lead to unexpected results.

**Comment by Cmt111** [comment]
> `u` is connectivity status that should only be 0 or 1. Setting `u` to non-binary values will lead to unexpected results.

Thank you for your response. What statement should be used to change the active power of the GENROU at a certain moment, please?

**Comment by jinningwang** [comment]
Check this example, https://docs.andes.app/en/latest/_examples/ex9.html

**Comment by cuihantao** [comment]
See the link Jinning shared. I'd like to add that active power output is a dependent variable of the stator voltages and currents. One cannot directly change the power output; it has to go through the references, either by changing the setpoint at turbine governors or at the generator (only when turbine governor is not connected for that generator).

**Comment by cuihantao** [comment]
Closing the issue for now due to lack of activity. Feel free to re-open it or post updates to Discussions.
