### ISSUE TITLE
Parameter updating does not reflect in export file

### ISSUE THREAD

**Issue by jinningwang** [CURENT/andes#527]
**Is your feature request related to a problem? Please describe.**
If a NumParam is updated by ``Model.set()``, it remains to be the original value in exported file.

**Describe the solution you'd like**
Add parameter refreshing step to ensure the exported case file is consistent with the case itself.

**Describe alternatives you've considered**

**Additional context**
A PDF is attached to replicate the issue, [issue.pdf](https://github.com/CURENT/andes/files/14895661/issue.pdf)

In the following code, I notice there is ``Model.cache.refresh("df_in")``, but it doesn't address this issue.

https://github.com/CURENT/andes/blob/5ab784b75347a98d07c004e32d7c4b39d407ea2e/andes/io/xlsx.py#L57-L66

**Comment by cuihantao** [comment]
This is intended.

The docstring of `Model.set()` also mentions:

        To alter parameters and reflect it in the case file, use :meth:`alter`
        instead.

**Comment by cuihantao** [comment]
Cache is unrelated. Writing the output won't involve cache
