### ISSUE TITLE
Add an option to keep changed parameters

### ISSUE THREAD

**Issue by jinningwang** [CURENT/andes#579]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
For easier usage, we can add an option in the IO module to allow "overwrite original values". Thus, users can save all the changes they have made through "Mode.set". into the exported case file.

Proposed development:

Add a parameter `save_changes=False` to func "write()"
If true, overwrite the `Param.vin` by per unit conversion of `Param.v`

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by cuihantao** [comment]
The option already exists.

If a parameter is changed through "alter", it will be saved to the case
file when exported.

If a parameter is changed through "set", it will not be saved to the export.


Regards,
Hantao Cui

**Comment by cuihantao** [comment]
> Add a parameter `save_changes=False` to func "write()" If true, overwrite the `Param.vin` by per unit conversion of `Param.v`

This is going to fail. If a field, say, generator's `M` is overwritten by the per-unit converted values, the next time the data is loaded, `M`'s value will again be treated as in the machine base and then converted to system per unit, which will be wrong. There is no way to specify whether input data has been converted to per unit or not - we can but don't want to do it, because it creates more confusion.

**Comment by jinningwang** [comment]
The proposed change to my mind looks like this:

https://github.com/jinningwang/andes/blob/70c9cb57d0a6cadec65086d1f9011a02b99a3fa0/andes/core/model/model.py#L555C1-L565C1

A quick demo is attached: [dev_alter.pdf](https://github.com/user-attachments/files/17804022/dev_alter.pdf)

Let me know if this makes sense to you.

**Comment by cuihantao** [comment]
Thanks. Can you respond to my replies, please?

**Comment by cuihantao** [comment]
Which one is better, the proposed API or the same API as "set", which takes an "attr"?

**Comment by jinningwang** [comment]
> This is going to fail. If a field, say, generator's M is overwritten by the per-unit converted values, the next time the data is loaded, M's value will again be treated as in the machine base and then converted to system per unit, which will be wrong.

Yes, I also saw this in my local test.

> There is no way to specify whether input data has been converted to per unit or not - we can but don't want to do it, because it creates more confusion.

Yes, so I made changes to method `alter`.

> Which one is better, the proposed API or the same API as "set", which takes an "attr"?

Let me think about this. If second one is better, I can make a notebook demo as a clarification.

**Comment by jinningwang** [comment]
The purpose of my proposed change is to eliminate the need for users to handle per-unit conversions themselves when adjusting parameters. At the same time, they can maintain all changes in a dumped file.

This change is motivated by my own confusion when manipulating parameters, as I feel this approach is less confusing.

Welcome any further comments or suggestions if I have overlooked anything.

**Comment by cuihantao** [comment]
> The point in my proposed change is that users would not need to bother
with per_unit conversion themself when manipulating the parameters, but the
same time they can also keep all the changes in a dumped file.

I understand. The goal is to be able to specify values after the per-unit
conversion and save it properly to a case file.

Using the same signature for `set` and `alter` reduces cognitive burden.
`set` is for setting values but will not be saved to cases. `alter` will
set the values and affect the dump. In `alter`, add an `attr` argument and
default it to `v`. If the input is `vin`, handle it in the function as you
did.

Regards,
Hantao Cui

**Comment by jinningwang** [comment]
Thanks for this informative comment, I'll make a quick development in short.
