### ISSUE TITLE
Wording issue in model ``ACEc``

### ISSUE THREAD

**Issue by jinningwang** [CURENT/andes#585]
**Describe the bug**

There seems to be a trivial wording issue with the model ``ACEc``. Given NERC's definition (Balancing and Freuqneyc Control - Bias (B) vs. Frequency Response (Beta), available at: https://www.nerc.com/comm/OC/BAL0031_Supporting_Documents_2017_DL/NERC%20Balancing%20and%20Frequency%20Control%20040520111.pdf)

> There is often confusion in the Industry when discussing Frequency Bias and Frequency Response. Even though there are similarities between the two terms, Frequency Bias (B) is not the same as Frequency Response (β).

> Frequency Response, defined in the NERC Glossary7, is the mathematical expression of the net change in a Balancing Area’s Net Actual Interchange for a change in interconnection frequency. It is a fundamental reliability service provided by a combination of governor and load response. Frequency Response represents the actual MW primary response contribution to stabilize frequency following a disturbance.

> Bias is an approximation of β used in the ACE equation. Bias prevents AGC withdrawal of frequency support following a disturbance. If B and β were exactly equal, a Balancing Authority would see no change in ACE following a frequency decline, even though it provided a MW contribution to stabilize frequency. 

https://github.com/CURENT/andes/blob/5ab784b75347a98d07c004e32d7c4b39d407ea2e/andes/models/area.py#L51-L60

Suggest change: 
``tex_name=r'\beta'`` -> ``tex_name='B'``

**To Reproduce**

N/A

**Expected behavior**

N/A

**Desktop (please complete the following information):**

N/A

**pip packages (please paste the output from `pip list`)**

N/A

**Additional context**

N/A

**Comment by cuihantao** [comment]
Jinning, thanks!!
